// src/app/components/calculation-row.component/calculation-row.component.ts
import { Component, OnInit, Input } from "@angular/core";
import { ICalculationItem } from "../../interfaces/i-calculation-item";
import { EventManagerService } from "../../services/event-manager.service";

@Component({
    selector: "[app-calculation-row]",
    templateUrl: "calculation-row.component.html"
})
export class CalculationRowComponent implements OnInit {
    @Input() item: ICalculationItem;
    @Input() disabled: boolean;
    
    constructor(private eventManager: EventManagerService) { }

    ngOnInit() {
    }

    private switchToEditMode(id): void {
        this.eventManager.NotifyThatCalculationItemIsReadyToBeOpenedForEditing(id);
    }

    private remove(id: string): void {
        this.eventManager.NotifyThatCalculationItemIsReadyToBeRemoved(id);
    }

    private pay(id: string): void {
        this.eventManager.NotifyThatCalculationItemIsReadyToBePaid(id);
    }
}

<ng-container>
    <td></td>
    <td><button [disabled]="disabled" (click)="switchToEditMode(item.id)">Ed</button></td>
    <td>{{item.sum}}</td>
    <td>{{item.aim}}</td>
    <td><input type="checkbox" [checked]="item.isPaid" (click)="pay(item.id)" [disabled]="disabled" /></td>
    <td><button class="remove" (click)="remove(item.id)" [disabled]="disabled">Rm</button></td>
</ng-container>

// src/components/calculation-row.tsx
import * as React from "react";
import { ICalculationItem } from "../interfaces/i-calculation-item";
import { SyntheticEvent } from "react";

export interface ICalculationRowComponentProps {
    item: ICalculationItem,
    handleRemoveRowClick: () => void;
    handleSwitchPaymentStatusClick: () => void;
}

export class CalculationRowComponent extends React.Component<ICalculationRowComponentProps> {
    constructor(props: any) {
        super(props);
    }

    render() {
        return (
            <tr className={this.props.item.isPaid ? "is-paid": undefined}>
                <td></td>
                <td></td>
                <td>{this.props.item.sum}</td>
                <td>{this.props.item.aim}</td>
                <td><input type="checkbox" checked={this.props.item.isPaid} onClick={this.props.handleSwitchPaymentStatusClick}/></td>
                <td><button className="remove" onClick={this.props.handleRemoveRowClick}>Rm</button></td >
            </tr>
        );
    }
}
